# -*- coding: utf-8 -*-
"""olx2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOc28SlI3BNXtyQCJItxQlpboYmaXRJ9
"""

# url ==> https://www.olx.com.eg/ajax/misc/contact/phone/bYhjS/
# https://www.olx.com.eg/ajax/misc/contact/phone/{id}  
# https://www.olx.com.eg/ad/town-house-corner-307-m2-for-sale-in-vilette-IDbYhjS.html

# libs
from bs4 import BeautifulSoup as sp
from requests import get
import lxml
import json

def get_phone(refurl):
    id = refurl[refurl.index('ID'):].strip('ID').strip('.html')
    h = {
        'accept': '*/*',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.9',
        'referer':refurl ,
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'

        }
    
    url = f'https://www.olx.com.eg/ajax/misc/contact/phone/{id}'
    phone = get(url,headers=h).content
    try:
        phone = json.loads(phone)['value'].replace(' ','')
        return phone
    except:
        pass

categories = ['vehicles', 'properties', 'mobile-phones-tablets-accessories-numbers', 'electronics-home-appliances', 'home-furniture-decor', 'fashion-beauty', 'pets', 'kids-babies', 'books-sports-hobbies', 'jobs', 'business-industrial-agriculture', 'services'] 
def get_ads(category,pages_count):
    ads_links = []
    for page in range(pages_count):
        refurl= f'https://www.olx.com.eg/{category}/?page={page+1}'
        if page==1:
          refurl= f'https://www.olx.com.eg/{category}/'

        ajx_url = 'https://www.olx.com.eg/ajax/search/list/'
        print(f'=========={page+1}==========')
        print(refurl)
        headers= {
                
                'accept': '*/*',
                'accept-encoding': 'gzip, deflate, br',
                'accept-language': 'en-US,en;q=0.9',
                'referer':refurl,
                'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
                }
        response = get(ajx_url,headers=headers)
        soup = sp(response.content,'lxml')
        ads = soup.find_all('div',class_='ads__item__info')
        for ad in ads:
            ads_links.append(ad.a['href'] )
           
    return ads_links
        



def main():

    phones =[]
    for category in range(len(categories)):
      print( f"{category}- {categories[category]}")
    chose = int(input('chose your category by number: '))
    category = categories[chose]
    pages_count = int(input('chose your page count: '))
    ads_links = get_ads(category,pages_count)
    for ad in ads_links :
        phone = get_phone(ad)
        if phone != None:
            print(phone)
            phones.append(phone)
    print('done') 
    final_phones = list(dict.fromkeys(phones))
    phones_f = open('phones.txt','w')

    for p in final_phones:

      phones_f.write(p+'\n')
    phones_f.close()

# url = 'https://www.olx.com.eg/'
# headers= {
#                 'accept': '*/*',
#                 'accept-encoding': 'gzip, deflate, br',
#                 'accept-language': 'en-US,en;q=0.9',
                
#                 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
#                 }
# response = get(url,headers=headers)

# soup = sp(response.content,'lxml')
# items = soup.find_all('div',class_='item')
# categories =[]
# for i in items :
#     category = i.a['data-code']

#     categories.append(category)
# print(categories)
# categories=['vehicles', 'properties', 'mobile-phones-tablets-accessories-numbers', 'electronics-home-appliances', 'home-furniture-decor', 'fashion-beauty', 'pets', 'kids-babies', 'books-sports-hobbies', 'jobs', 'business-industrial-agriculture', 'services']

# for category in range(len(categories)):
#       print( f"{category} {categories[category]}")
if __name__ == '__main__':
  main()

